import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor : "red", height : "50px", textAlign : "center"}}>Header</header>
        {children}
        <footer style={{backgroundColor : "teal", height : "50px", textAlign : "center"}}>Footer</footer>
      </body>
    </html>
  );
}